config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:index, :show, :list_abilities_interests] do
    collection do
      get 'close_window'
      get 'notifications'
      get 'messages'
    end
  end

  authenticated :user do
    root :to => "homee#index"
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  resources :conversations do
    resources :messages
  end

  resources :topics do
    collection do
      post 'create_post'
      patch 'update_post'
      delete 'destroy_post'
      get 'make_important'
      get 'make_not_important'
    end
  end
  resources :friends do
    collection do
      get 'friend_request'
      get 'cancel_request'
      delete 'refuse_request'
      get 'accept_request'
    end
  end
  resources :publications do
    collection do
      post 'create_comment'
      patch 'update_comment'
      delete 'destroy_comment'
    end
  end

  resources :tasks do
    collection do
      get 'move_do'
      get 'move_doing'
      get 'move_done'
      get 'accept'
      get 'enter_request'
      get 'quit_request'
      get 'quit_accept'

      patch 'quit_request'
      get 'quit_refuse'
      get 'refuse'
    end
  end
  resources :interests
  resources :abilities
  get 'projects/search_result' => 'projects#search_result', as: :search_result
  resources :projects do
    collection do
        get 'share_publication'
        get 'list_projects'
        get 'send_request'
        get 'accept_request'
        get 'refuse_request'
        get 'without_project'
        get 'follow'
        get 'unfollow'
      end
    end
  get 'chat_refresh' => 'homee#chat_refresh', as: :chat_refresh
  get 'projects/:id/members' => 'projects#members', as: :members_project
  get 'projects/:id/about' => 'projects#about', as: :about_project
  get 'projects/:id/request_list' => 'projects#request_list', as: :request_list
  get 'projects/:id/forum/create_topic' => 'topics#new', as: :create_topic
  get 'projects/:id/new_publication' => 'publications#new', as: :create_publication
  get 'projects/:id/new_comment' => 'publications#new_comment', as: :new_comment
  get 'projects/:id_project/publications/:id_publication/edit_comment' => 'publications#edit_comment', as: :edit_comment
  get 'projects/:id/new_task' => 'tasks#new', as: :create_task
  get 'projects/:id/forum/' => 'topics#index', as: :list_topics
  get 'projects/:id/forum/:id_topic' => 'topics#show_topic', as: :show_topic
  get 'projects/:id/forum/:id_topic/new_post' => 'topics#new_post', as: :new_post
  get 'projects/:id/forum/:id_topic/show_topic/:id_post' => 'topics#edit_post', as: :edit_post
  get 'projects/:id/tasks/' => 'tasks#index', as: :list_tasks
  get 'projects/:id/tasks/:id_task/edit' => 'tasks#edit', as: :edit_tasks
  get 'projects/:id/tasks/:id_task' => 'tasks#show', as: :show_tasks
  get 'cep/:cep' => 'cep#verificar'
  get 'users/:id/about' => 'users#about', as: :about_user
  get 'users/:id/friends' => 'users#friends', as: :friends_user
  get 'users/:id/projects' => 'users#projects', as: :projects_user
  get 'user/:id' => 'users#list_abilities_interests', as: :list_preferences

  

  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'sessions' => 'sessions#create', :as => 'login'
        post 'registrations' => 'registrations#create', :as => 'register'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
    end
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
	include PublicActivity::Model
	belongs_to :project
	belongs_to :user

	has_many :assists, dependent: :destroy
  	has_many :users, :through => :assists
  	
  	has_many :activities, as: :trackable, class_name: 'PublicActivity::Activity', dependent: :destroy


end

app/controllers/api/v1/tasks_controller.rb
class Api::V1::TasksController < ApplicationController
  skip_before_filter :verify_authenticity_token,
                     :if => Proc.new { |c| c.request.format == 'application/json' }

  before_filter :authenticate_user!
  
  def index
    @tasks = current_user.tasks

    render :text => '{
    "success": true,
    "info":"ok",
    "data": {
              "tasks":[
                        {"title":"Complete the app"},
                        {"title":"Complete the tutorial"}
                      ]
            }
  }'

  end

  def create
    @task = current_user.tasks.build(params[:task])
    if @task.save
      @task
    else
      render :status => :unprocessable_entity,
             :json => { :success => false,
                        :info => @task.errors.full_messages,
                        :data => {} }
    end
  end

  def open
    @task = current_user.tasks.find(params[:id])
    @task.open!
  rescue ActiveRecord::RecordNotFound
    render :status => 404,
           :json => { :success => false,
                      :info => 'Not Found',
                      :data => {} }
  end

  def complete
    @task = current_user.tasks.find(params[:id])
    @task.complete!
  rescue ActiveRecord::RecordNotFound
    render :status => 404,
           :json => { :success => false,
                      :info => 'Not Found',
                      :data => {} }
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_action :set_task, only: [:update, :destroy]
	
	def new
		@task = Task.new
		@project = params[:id]
		@users = Project.find(params[:id]).users.includes(:members).where("situation = 1")

	end

	def index
		@project = Project.find(params[:id])
		@users = @project.users.includes(:members).where("situation = 1")
		@tasks = @project.tasks
		@task = Task.new
	end

	def move_do
		task = Task.find(params[:id_task])
		task.situation = "A Fazer"
		task.save
		redirect_to list_tasks_path(task.project.id)
	end

	def move_doing
		task = Task.find(params[:id_task])
		task.situation = "Fazendo"
		task.save
		redirect_to list_tasks_path(task.project.id)
	end

	def move_done
		task = Task.find(params[:id_task])
		task.situation = "Feita"
		task.save
		redirect_to list_tasks_path(task.project.id)
	end

    def create
	    @task = Task.new(task_params)
	    @task.user_id = current_user.id

	    respond_to do |format|
	      if @task.save

	      	@task.project.members.each do |member|
	      		if current_user.id != member.user_id
	      			Assist.where(task_id: @task.id).each do |assist|
	      				if assist.user_id == member.user_id
	      					@task.create_activity(:invite_task, :owner => User.find(assist.user_id))	
	      				elsif assist.user_id != member.user_id
	      					@task.create_activity(:create, :owner => User.find(member.user_id))
	      				end
	      			end
	      		end
	      	end

	        format.html { redirect_to list_tasks_path(@task.project.id), notice: 'Tarefa criada com sucesso.' }
	        format.json { render :show, status: :created, location: @task }
	      else
	        format.html { render :new }
	        format.json { render json: @task.errors, status: :unprocessable_entity }
	      end
	    end
  	end



    def edit
    	  @task = Task.find(params[:id_task])
    	  @users = Project.find(params[:id]).users.includes(:members).where("situation = 1")
    end

    def accept
	    assist = Assist.find(params[:id_assist])
	    assist.status = 1
	    assist.save
	    redirect_to root_path
    end

	def quit_request
		assist = Assist.find(params[:id_assist])
		assist.reason = params[:assist][:reason]
		assist.status = 3
		assist.save
		redirect_to assist.task.project
	end

	def enter_request
		assist = Assist.new
		assist.user_id = current_user.id
		assist.task_id = params[:id_task]
		assist.status = 2
		assist.save
		redirect_to assist.task.project
	end

	def quit_accept
		assist = Assist.find(params[:id_assist])

		project = assist.task.project
		assist.destroy
		redirect_to project

	end

	def quit_refuse
		assist = Assist.find(params[:id_assist])
		assist.status = 1
		assist.save
		redirect_to assist.task.project

	end

	def refuse
		assist = Assist.find(params[:id_assist])
		project = assist.task.project
		assist.destroy
		redirect_to project

	end

    def update
    	  respond_to do |format|
	      if @task.update(task_params)
	        format.html { redirect_to list_tasks_path(@task.project.id), notice: 'Tarefa atualizada com sucesso.' }
	        format.json { render :show, status: :ok, location: @task }
	      else
	        format.html { render :edit }
	        format.json { render json: @task.errors, status: :unprocessable_entity }
	      end
	    end
    end


    def destroy
	    project = @task.project
	    @task.destroy
	    redirect_to list_tasks_path(project.id)
	    flash[:success] = 'Tarefa excluída com sucesso.'
	end

    def show
    	@task = Task.find(params[:id_task])
    end


    private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:description, :user_id, :project_id, :location, :date_start, :date_end, :situation,:reason, :user_ids => [])
    end   
end      

app/views/tasks/_edit_task.html.erb
<div class="modal fade" id="edit_task_<%= task.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Editando Tarefa</h4>
      </div>
      <%= simple_form_for task do |f| %>
      <div class="modal-body">
          <%= f.input :description, label: false%>
          <%= f.input :situation, collection: ["A Fazer", "Fazendo", "Feita"], as: :select, include_blank: false %>
            <h5 style="text-align: left; margin-top: 7px;"> Responsáveis: </h5>
            <div class="row" style= "padding: 20px;">
              <% users.each do |user| %>
                <a href="javascript:;" onclick="setUser<%=task.id%>(<%= user.id %>)">
                <div class="col-md-4" style="margin-bottom: 10px;padding-right: 1px;">
                  <div class="row" id="user_task user_img_<%=task.id%>_<%=user.id%>" style="margin: 0px">
                  <%= image_tag(user.avatar, class: "img-responsive", style: "width: 30px; height: 30px; float: left; margin-right: 5px;") %>
                  <h5 style="text-align: left; margin-top: 7px;"> <%= user.name %> </h5>
                  </div>
                </div>
                </a>

              <% end %>
            </div>

          

          <%= f.input :users, :as => :check_boxes do %>
            <%= f.collection_check_boxes :user_ids, users, :id, :name do |b| %>
              <%= b.check_box(:id => "input_#{task.id}_#{b.value}") + b.label %>
           <% end %>
          <% end %>  
      </div>

      <div class="modal-footer">
        <%= f.submit "Salvar", class: "btn btn-default button_project button_submit"%>
        <button type="button" class="btn btn-default button_project" data-dismiss="modal">Fechar</button>
      </div>
      <% end %>

    </div>
  </div>
</div>

<script>

  setTasks<%= task.id %>();
  function setTasks<%= task.id %>(){
    var clas;
    var check;
    var id;
    <% users.each do |user|%>
      id = "input_<%=task.id%>_<%=user.id%>";
      check = document.getElementById(id);
      id_div = "#user_img_<%=task.id%>_<%=user.id%>";
      if (check.checked){
        $(id_div).addClass("user_task_selected");
      }
    <% end %>


  };
    function setUser<%= task.id %>(id){
    var image = "#user_img_<%=task.id%>_"+id;
    var id_check = "input_<%=task.id%>_"+id;
    var check_box = document.getElementById(id_check);

    if ($(image).hasClass("user_task_selected")){
      $(image).removeClass("user_task_selected");
      check_box.checked = false;
    }else{
      $(image).addClass("user_task_selected"); 
      check_box.checked = true;
    }
  };
</script>

app/views/tasks/_form.html.erb
<% @assist = assist %>
<%= simple_form_for @assist, :url => quit_request_tasks_path(:id_assist => @assist) do |f| %>
  <% if @assist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assist.errors.count, "error") %> prohibited this assist from being saved:</h2>

      <ul>
      <% @assist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :reason %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= simple_form_for @task do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :description %>
  <%= f.input :location %>
    <%= f.association :users, label_method: :email, value_method: :id, collection: @users, as: :check_boxes %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/index.html.erb
<%= render 'projects/projectnav'%>

<div class="water" style="border: 1px solid #EAEAEA">
  <div class="title-blue-publication " style="padding-top: 15px;">
      <% if current_user == @project.user %>
      <div style="text-align: left; margin-left: -5px; margin-bottom: 10px;"> <a href="#" class="btn button_project button_inactive" data-toggle="modal" data-target="#newtask">  Nova Tarefa  </a> </div>
      <% end %>
        <div class="modal fade" id="newtask" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Nova Tarefa</h4>
              </div>
              <%= simple_form_for @task do |f| %>
              <div class="modal-body">
                  <%= f.input :description, label: "Descrição"%>
                  <%= f.input :situation, label: "Situação", collection: ["A Fazer", "Fazendo", "Feita"], as: :select, include_blank: false %>
                  <%= f.input :project_id, :as => :hidden, :input_html => { :value =>  @project.id } %>
                    <h5 style="text-align: left; margin-top: 7px;"> Responsáveis: </h5>
                    <div class="row" style= "padding: 20px;">
                      <% @users.each do |user| %>
                        <a href="javascript:;" onclick="setUser(<%= user.id %>)" class="user_link">
                        <div class="col-md-4" id="user_task" style="margin-bottom: 10px;padding-right: 1px;">
                          <div class="row" id="user_img_<%= user.id %>" style="margin: 0px">
                          <%= image_tag(user.avatar, class: "img-responsive", style: "width: 30px; height: 30px; float: left; margin-right: 5px;") %>
                          <h5 style="text-align: left; margin-top: 7px;"> <%= user.name %> </h5>
                          </div>
                        </div>
                        </a>
                      <% end %>
                    </div>
                  <div style="display: none;"><%= f.association :users, label_method: :email, value_method: :id, collection: @users, as: :check_boxes %></div>    
              </div>
              <div class="modal-footer">
                <%= f.submit "Salvar", class: "btn btn-default button_project button_submit"%>
                <button type="button" class="btn btn-default button_project" data-dismiss="modal">Fechar</button>
              </div>
              <% end %>
            </div>
          </div>
        </div>


    <div class="row" style="padding: 6px; text-align: left;">
      <div class="col-md-4" style="padding-left:0px;padding-right: 0px; padding-top: 7px; border-top: 2px solid #0066CC">
        <h5 style="text-align: left; margin-left: 5px; font-size: 16px; text-align: center;"> A Fazer </h5>
        <% @tasks.where(:situation => "A Fazer").each do |p| %>
          <div class="row" style="border: 1px solid #CCC; margin: 3px; margin-top: 6px; border-top: 2px solid #0066CC; border-radius: 5px; padding: 3px;">
            <div style="width:150px; float: left">
            <p style="font-size: 15px;  margin-bottom: 4px"> <%= p.description %> </p>
            <% p.users.each do |user|%>
              <%= image_tag(user.avatar, style: "height: 25px; width: 25px") %>
            <% end %>
            </div>
            <div style="width:11px; float:right">
              <% if current_user == @project.user || p.users.include?(current_user)%>
              <span class="dropdown-toggle" style="cursor: pointer" id="dropdownMenu<%= p.id %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                <span class="glyphicon glyphicon-pencil drop_icon" style="font-size: 12px"> </span> 
              </span>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenu<%= p.id %>" style="top: auto !important; left: auto !important;">
                <% if current_user == @project.user %>
                  <li> <%= link_to 'Editar', "#", data:{toggle: 'modal', target: "#edit_task_#{p.id}"} %> </li>
                  
                  <li> <%= link_to 'Excluir', task_path(p), method: :delete, data: {confirm: "Tem certeza que deseja excluir essa publicação?"} %> </li>
                <% end %>
                  <li> <%= link_to 'Mover para Fazendo', move_doing_tasks_path(id_task: p.id) %> </li>

                  <li> <%= link_to 'Mover para Concluído', move_done_tasks_path(id_task: p.id) %> </li>
              </ul>
              <% end %>
            </div> 
          </div>

          <%= render 'edit_task', task: p, users: @users%>

        <% end %>

      </div>

      <div class="col-md-4" style="padding-left:0px;padding-right: 0px; padding-top: 7px; border-top: 2px solid #FFCC66">
        <h5 style="text-align: left; margin-left: 5px; font-size: 16px; text-align: center;"> Fazendo </h5>
        <% @tasks.where(:situation => "Fazendo").each do |p| %>
            <div class="row" style="border: 1px solid #CCC; margin: 3px; margin-top: 6px; border-top: 2px solid #FFCC66; border-radius: 5px; padding: 3px;">
            <div style="width:150px; float: left">
            <p style="font-size: 15px; margin-bottom: 4px"> <%= p.description %> </p>
            <% p.users.each do |user|%>
              <%= image_tag(user.avatar, style: "height: 25px; width: 25px") %>
            <% end %> 
            </div>
            <div style="width:11px; float:right">
              <% if current_user == @project.user || p.users.include?(current_user)%>
              <span class="dropdown-toggle" style="cursor: pointer" id="dropdownMenu<%= p.id %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                <span class="glyphicon glyphicon-pencil drop_icon" style="font-size: 12px"> </span> 
              </span>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenu<%= p.id %>" style="top: auto !important; left: auto !important;">
                <% if current_user == @project.user %>
                  <li> <%= link_to 'Editar', "#", data:{toggle: 'modal', target: "#edit_task_#{p.id}"} %> </li>
                  
                  <li> <%= link_to 'Excluir', task_path(p), method: :delete, data: {confirm: "Tem certeza que deseja excluir essa publicação?"} %> </li>
                <% end %>
                  <li> <%= link_to 'Mover para A Fazer', move_do_tasks_path(id_task: p.id) %> </li>

                  <li> <%= link_to 'Mover para Concluído', move_done_tasks_path(id_task: p.id) %> </li>
              </ul>
              <% end %>
            </div>
          </div>

          <%= render 'edit_task', task: p, users: @users%>

        <% end %>

      </div>

        <div class="col-md-4" style="padding-left:0px;padding-right: 0px; padding-top: 7px; border-top: 2px solid #00CC66">
        <h5 style="text-align: left; margin-left: 5px; font-size: 16px; text-align: center;"> Concluídas </h5>
        <% @tasks.where(:situation => "Feita").each do |p| %>
          <div class="row" style="border: 1px solid #CCC; margin: 3px; margin-top: 6px; border-top: 2px solid #00CC66; border-radius: 5px; padding: 3px;">
            <div style="width:150px; float: left">
            <p style="font-size: 15px;  margin-bottom: 4px"> <%= p.description %> </p>
            <% p.users.each do |user|%>
              <%= image_tag(user.avatar, style: "height: 25px; width: 25px") %>
            <% end %>
            </div>
            <div style="width:11px; float:right">
               <% if current_user == @project.user || p.users.include?(current_user)%>
              <span class="dropdown-toggle" style="cursor: pointer" id="dropdownMenu<%= p.id %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                <span class="glyphicon glyphicon-pencil drop_icon" style="font-size: 12px"> </span> 
              </span>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenu<%= p.id %>" style="top: auto !important; left: auto !important;">
                <% if current_user == @project.user %>
                  <li> <%= link_to 'Editar', "#", data:{toggle: 'modal', target: "#edit_task_#{p.id}"} %> </li>
                  
                  <li> <%= link_to 'Excluir', task_path(p), method: :delete, data: {confirm: "Tem certeza que deseja excluir essa publicação?"} %> </li>
                <% end %>
                  <li> <%= link_to 'Mover para A Fazer', move_do_tasks_path(id_task: p.id) %> </li>

                  <li> <%= link_to 'Mover para Fazendo', move_doing_tasks_path(id_task: p.id) %> </li>
              </ul>
              <% end %>
            </div>
          </div>

          <%= render 'edit_task', task: p, users: @users%>
        <% end %>


      </div>
    </div>
  </div>
</div>

<script>
  limpar();

  function limpar(){
    var check;
    var id;
    <% @users.each do |user|%>
      id = "task_user_ids_" + "<%= user.id %>";
      check = document.getElementById(id);
      check.checked = false;
    <% end %>
  };

  function setUser(id){
    var image = "#user_img_"+id;
    var id_check = "task_user_ids_" + id;
    var check_box = document.getElementById(id_check);

    if ($(image).hasClass("user_task_selected")){
      $(image).removeClass("user_task_selected");
      check_box.checked = false;
    }else{
      $(image).addClass("user_task_selected"); 
      check_box.checked = true;
    }
  };

</script>

<!--
<h1> Forum </h1>

<% @tasks.each do |p| %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= p.description %></h3>
  </div>
  <div class="panel-body">
    <%= p.location %>
  </div>
  <div class="panel-body">
    <%= p.situation %>
  </div>
  <div>
  <%= p.user.email %>
  </div>
  <div>
    <% p.users.each do |user| %>
      <%= user.email %>
    <% end %>
  </div>


  <div class="panel-body">
  	<%= link_to "Editar", edit_tasks_path(id_task: p.id) %>
  	<br>
  	<%= link_to "Deletar", task_path(id_task: p.id), method: :delete, data: { confirm: 'Are you sure?'} %>
    <br>
    <br><br>
  
    Solicitacoes para Participar:<br>
    <% p.assists.where(status: 2).each do |a|%>
      <%= a.user.email %>
      <%= link_to "Aceitar participacao", accept_tasks_path(id_assist: a.id) %>
      <%= link_to "Recusar participacao", refuse_tasks_path(id_assist: a.id) %>
      <br>
    <% end %>
<br>
    Solicitacoes para Sair:<br>
    <% p.assists.where(status: 3).each do |a|%>
      <%= a.user.email %>
      <br>
      <%= a.reason %>
      <br>
      <%= link_to "Aceitar saida", quit_accept_tasks_path(id_assist: a.id) %>
      <%= link_to "Recusar saida", quit_refuse_tasks_path(id_assist: a.id) %>
      <br>
    <% end %>

  </div>

</div>

<% end %>


<br>
<br>

<%= link_to "Criar nova Tarefa",create_task_path %>

-->

app/views/tasks/new.html.erb
<h1>New Task</h1>


<%= simple_form_for @task do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :description %>
  <%= f.input :location %>
  <%= f.input :project_id, :as => :hidden, :input_html => { :value =>  @project } %>
  <%= f.association :users, label_method: :email, value_method: :id, collection: @users, as: :check_boxes %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/show.html.erb
    <%= @task.description %>
    <br>
    <%= @task.location %>
    <br>
    <%= @task.date_start %>
    <br>
    <%= @task.date_end %>
    <br>
    <%= @task.situation %>
    <br>
    <%= @task.user.email %>

<%= link_to "Editar", edit_tasks_path(id_task: @task.id) %>