config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:index, :show, :list_abilities_interests] do
    collection do
      get 'close_window'
      get 'notifications'
      get 'messages'
    end
  end

  authenticated :user do
    root :to => "homee#index"
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  resources :conversations do
    resources :messages
  end

  resources :topics do
    collection do
      post 'create_post'
      patch 'update_post'
      delete 'destroy_post'
      get 'make_important'
      get 'make_not_important'
    end
  end
  resources :friends do
    collection do
      get 'friend_request'
      get 'cancel_request'
      delete 'refuse_request'
      get 'accept_request'
    end
  end
  resources :publications do
    collection do
      post 'create_comment'
      patch 'update_comment'
      delete 'destroy_comment'
    end
  end

  resources :tasks do
    collection do
      get 'move_do'
      get 'move_doing'
      get 'move_done'
      get 'accept'
      get 'enter_request'
      get 'quit_request'
      get 'quit_accept'

      patch 'quit_request'
      get 'quit_refuse'
      get 'refuse'
    end
  end
  resources :interests
  resources :abilities
  get 'projects/search_result' => 'projects#search_result', as: :search_result
  resources :projects do
    collection do
        get 'share_publication'
        get 'list_projects'
        get 'send_request'
        get 'accept_request'
        get 'refuse_request'
        get 'without_project'
        get 'follow'
        get 'unfollow'
      end
    end
  get 'chat_refresh' => 'homee#chat_refresh', as: :chat_refresh
  get 'projects/:id/members' => 'projects#members', as: :members_project
  get 'projects/:id/about' => 'projects#about', as: :about_project
  get 'projects/:id/request_list' => 'projects#request_list', as: :request_list
  get 'projects/:id/forum/create_topic' => 'topics#new', as: :create_topic
  get 'projects/:id/new_publication' => 'publications#new', as: :create_publication
  get 'projects/:id/new_comment' => 'publications#new_comment', as: :new_comment
  get 'projects/:id_project/publications/:id_publication/edit_comment' => 'publications#edit_comment', as: :edit_comment
  get 'projects/:id/new_task' => 'tasks#new', as: :create_task
  get 'projects/:id/forum/' => 'topics#index', as: :list_topics
  get 'projects/:id/forum/:id_topic' => 'topics#show_topic', as: :show_topic
  get 'projects/:id/forum/:id_topic/new_post' => 'topics#new_post', as: :new_post
  get 'projects/:id/forum/:id_topic/show_topic/:id_post' => 'topics#edit_post', as: :edit_post
  get 'projects/:id/tasks/' => 'tasks#index', as: :list_tasks
  get 'projects/:id/tasks/:id_task/edit' => 'tasks#edit', as: :edit_tasks
  get 'projects/:id/tasks/:id_task' => 'tasks#show', as: :show_tasks
  get 'cep/:cep' => 'cep#verificar'
  get 'users/:id/about' => 'users#about', as: :about_user
  get 'users/:id/friends' => 'users#friends', as: :friends_user
  get 'users/:id/projects' => 'users#projects', as: :projects_user
  get 'user/:id' => 'users#list_abilities_interests', as: :list_preferences

  

  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'sessions' => 'sessions#create', :as => 'login'
        post 'registrations' => 'registrations#create', :as => 'register'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
    end
  end

end

app/models/friend.rb
class Friend < ActiveRecord::Base
#include PublicActivity::Model
 
belongs_to :user
belongs_to :friend, class_name: "User"
has_many :activities, as: :trackable, class_name: 'PublicActivity::Activity', dependent: :destroy

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
	before_action :set_friend, only: [:destroy]
	def index
	end

	def friend_request
	    user_friend = User.find(params[:user])
	    #Criando a solicitação de amizade do usuário on-line
	    friend = Friend.new
	   	friend.user_id = current_user.id
	    friend.friend_id = user_friend.id
	    friend.status = 'request'
	    friend.save
	    flash[:success] = 'Sua solicitação foi realizada!'

	    #Criando a solicitação de amizade que fica pendente da
	    #aprovação do outro usuário
	    friend2 = Friend.new
	    friend2.user_id = user_friend.id
	    friend2.friend_id = current_user.id
	    friend2.status = 'pending'
	    friend2.save
	    #friend2.create_activity(:friend_request, :owner => User.find(friend2.user_id))
	    redirect_to users_path
	end

	def accept_request
		friend = Friend.find(params[:friend])
		friend.status = 'accept'
		friendship = Friend.where(user_id: friend.friend_id, friend_id: current_user.id, status: 'request').first
		friendship.status = 'accept'
		friendship.save
	    friend.save
	    redirect_to root_path
  	end

  	def refuse_request
  		friend = Friend.find(params[:friend])
  		friend1 = Friend.where(user_id: friend.friend_id, friend_id: friend.user_id, status: 'request').first
		friend1.delete
		friend.delete
		redirect_to root_path
  	end

  	def cancel_request

		friend = Friend.find(params[:friend])
		if friend.status == "accept"
			friendship = Friend.where(user_id: friend.friend_id, friend_id: friend.user_id, status: 'accept').first
		else
			friendship = Friend.where(user_id: friend.friend_id, friend_id: friend.user_id, status: 'pending').first
		end
		friendship.delete
		friend.delete
	    redirect_to root_path
 	 end


	def destroy
	   @friend.destroy
	   respond_to do |format|
	      format.html { redirect_to root_path, notice: 'Armizade desfeita com sucesso.' }
	      format.json { head :no_content }
	   end
	 end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friend_params
      params.require(:friend).permit(:requester_id, :destiny_id, :status)
    end
end

app/views/friends/_friends.html.erb
<% if Friend.where(user_id: current_user.id, status: 'accept')%>
	<% Friend.where(user_id: current_user.id, status: 'accept').each do |friend| %>
		<br>
		<%= friend.user_id %>
		<br>
		<%= friend.friend_id %>
		<br>
		<%= friend.status %>
		<br>
		<%= link_to 'Desfazer Amizade', cancel_request_friends_path(friend: friend), method: :delete, data: { confirm: 'Are you sure?'} %>
		<br>
	<% end %>
<% else %>
	Sem amigos!
<% end %>

app/views/friends/_pending_friends.html.erb
<% if Friend.where(user_id: current_user.id, status: 'pending') %>
	<% Friend.where(user_id: current_user.id, status: 'pending').each do |friend| %>
		<br>
		<%= friend.user_id %>
		<br>
		<%= friend.friend_id %>
		<br>
		<%= friend.status %>
		<br>
		<%= link_to 'Aceitar', accept_request_friends_path(friend: friend), data: { confirm: 'Are you sure?'} %>
		<br>
		<%= link_to 'Recusar', refuse_request_friends_path(friend: friend), method: :delete, data: { confirm: 'Are you sure?'} %>
		<br>
	<% end %>
<% else %>
	Não há novas solicitações de amizade para você
<% end %>

app/views/friends/_requested_friends.html.erb
<% if Friend.where(user_id: current_user.id, status: 'request') %>
	<% Friend.where(user_id: current_user.id, status: 'request').each do |friend| %>
		<br>
		<%= User.find(friend.friend_id).avatar %>
		<br>
		<%= User.find(friend.friend_id).name %>
		<br>
		<%= friend.status %>
		<br>
		<%= link_to 'Cancelar Solicitação', refuse_request_friends_path(friend: friend), method: :delete, data: { confirm: 'Are you sure?'} %>
		<br>
	<% end %>
<% else %>
	Sem solicitações de amizade
<% end %>

app/views/friends/index.html.erb
<h2>My Friends</h2>
	<br>
		<h3>Current Friends</h3>
		<%= render :partial => 'friends/friends' %>
		<h3>Requested Friends</h3>
		<%= render :partial => 'friends/requested_friends' %>
		<h3>Pending Friends</h3>
		<%= render :partial => 'friends/pending_friends' %>