config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:index, :show, :list_abilities_interests] do
    collection do
      get 'close_window'
      get 'notifications'
      get 'messages'
    end
  end

  authenticated :user do
    root :to => "homee#index"
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  resources :conversations do
    resources :messages
  end

  resources :topics do
    collection do
      post 'create_post'
      patch 'update_post'
      delete 'destroy_post'
      get 'make_important'
      get 'make_not_important'
    end
  end
  resources :friends do
    collection do
      get 'friend_request'
      get 'cancel_request'
      delete 'refuse_request'
      get 'accept_request'
    end
  end
  resources :publications do
    collection do
      post 'create_comment'
      patch 'update_comment'
      delete 'destroy_comment'
    end
  end

  resources :tasks do
    collection do
      get 'move_do'
      get 'move_doing'
      get 'move_done'
      get 'accept'
      get 'enter_request'
      get 'quit_request'
      get 'quit_accept'

      patch 'quit_request'
      get 'quit_refuse'
      get 'refuse'
    end
  end
  resources :interests
  resources :abilities
  get 'projects/search_result' => 'projects#search_result', as: :search_result
  resources :projects do
    collection do
        get 'share_publication'
        get 'list_projects'
        get 'send_request'
        get 'accept_request'
        get 'refuse_request'
        get 'without_project'
        get 'follow'
        get 'unfollow'
      end
    end
  get 'chat_refresh' => 'homee#chat_refresh', as: :chat_refresh
  get 'projects/:id/members' => 'projects#members', as: :members_project
  get 'projects/:id/about' => 'projects#about', as: :about_project
  get 'projects/:id/request_list' => 'projects#request_list', as: :request_list
  get 'projects/:id/forum/create_topic' => 'topics#new', as: :create_topic
  get 'projects/:id/new_publication' => 'publications#new', as: :create_publication
  get 'projects/:id/new_comment' => 'publications#new_comment', as: :new_comment
  get 'projects/:id_project/publications/:id_publication/edit_comment' => 'publications#edit_comment', as: :edit_comment
  get 'projects/:id/new_task' => 'tasks#new', as: :create_task
  get 'projects/:id/forum/' => 'topics#index', as: :list_topics
  get 'projects/:id/forum/:id_topic' => 'topics#show_topic', as: :show_topic
  get 'projects/:id/forum/:id_topic/new_post' => 'topics#new_post', as: :new_post
  get 'projects/:id/forum/:id_topic/show_topic/:id_post' => 'topics#edit_post', as: :edit_post
  get 'projects/:id/tasks/' => 'tasks#index', as: :list_tasks
  get 'projects/:id/tasks/:id_task/edit' => 'tasks#edit', as: :edit_tasks
  get 'projects/:id/tasks/:id_task' => 'tasks#show', as: :show_tasks
  get 'cep/:cep' => 'cep#verificar'
  get 'users/:id/about' => 'users#about', as: :about_user
  get 'users/:id/friends' => 'users#friends', as: :friends_user
  get 'users/:id/projects' => 'users#projects', as: :projects_user
  get 'user/:id' => 'users#list_abilities_interests', as: :list_preferences

  

  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'sessions' => 'sessions#create', :as => 'login'
        post 'registrations' => 'registrations#create', :as => 'register'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
    end
  end

end

app/models/publication.rb
class Publication < ActiveRecord::Base
	include PublicActivity::Model

	mount_uploader :image, AvatarUploader
	belongs_to :project
	belongs_to :user

	has_many :comments, dependent: :destroy
	has_many :shares, dependent: :destroy
	has_many :activities, as: :trackable, class_name: 'PublicActivity::Activity', dependent: :destroy

end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
	before_action :set_publication, only: [:show, :request_list, :edit, :update, :destroy]
  before_action :set_comment, only: [:edit_comment, :destroy_comment]

  def new
		@publication = Publication.new
    @project = params[:id]
	end

  def create
    @publication = Publication.new(publication_params)
    @publication.user_id = current_user.id
    respond_to do |format|
      if @publication.save

        @publication.project.users.each do |member|
          if current_user.id != member.id 
           @publication.create_activity(:create, :owner => member)
         end
        end

        format.html { redirect_to @publication.project, notice: 'Publicação criada com sucesso.' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @comment = Comment.new
  end

  def edit

  end

  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'Publicação atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end



  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    project = @publication.project
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Publicação excluída com sucesso.' }
      format.json { head :no_content }
    end
  end



  def new_comment
    @comment = Comment.new
    @project = params[:id_project]
    @publication = params[:id_publication]
  end

  def create_comment
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    publication = Publication.find(@comment.publication_id)
    respond_to do |format|
      if @comment.save

        @comment.publication.project.users.each do |member|
          if member.id != current_user.id
           @comment.create_activity(:create_comment, :owner => member)
         end
        end

        format.html { redirect_to project_path(publication.project_id), notice: 'Comentário adicionado com sucesso.' }
        format.json { render :show, status: :created, location: @comment}
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit_comment
    @comment = Comment.find(params[:id])
    @project = params[:id_project]
    @publication = params[:id_publication]
  end

  def update_comment
    @comment = Comment.find(params[:id])
    publication = Publication.find(@comment.publication_id)
    @comment.update(comment_params)
    redirect_to publication, notice: 'Comentário atualizado com sucesso.'
  end

  def destroy_comment
    @comment = Comment.find(params[:id])
    publication = Publication.find(@comment.publication_id)
    @comment.destroy
    redirect_to publication, notice: 'Comentário excluído com sucesso.'
  end 

	private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end
    
    def publication_params
      params.require(:publication).permit(:description, :user_id, :project_id, :image)
    end
    
    def comment_params
      params.require(:comment).permit(:description, :user_id, :publication_id, :project_id)
    end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<%= simple_form_for @publication do |f| %>
  <% if @publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
      <% @publication.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :description %>
  <%= f.input :image %>
  <%= f.input :project_id, :as => :hidden, :input_html => { :value =>  @project } %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publications/_newpublication.html.erb
<div class="water" style="border: 1px solid #EAEAEA">
	<div class="title-blue-publication ">
		<%= simple_form_for @publication do |f| %>
		<div class="row" >
			<div class="col-md-1" >

			<div style="width: 32x; border: 1px solid #DDD; height: 32px;line-height:28px;float:left;margin-left: -5px;margin-top: 5px;margin-right: 5px;">
			    <%= image_tag(current_user.avatar, class: "newpostavatar") %>
			</div>

			</div>
			<div class="col-md-11 public_in" style="margin-left: -10px">
			<%= f.input :description, label: false, input_html:{style: 'width: 440px; height: 40px; resize: none;', id: "public_textarea", placeholder: "Qual atividade você realizou hoje?"} %>
			
			<%= f.input :image, label: false, input_html:{class: "", id: 'fileupload-example-4', onchange:"imagePreview(this)"}  %>
				<label id="fileupload-example-4-label " for="fileupload-example-4" style="float:right; width: 20px; margin-top: 5px">
					<span class="glyphicon glyphicon-camera add_img" style="font-size: 32px; cursor: pointer;" ></span>
				</label>

				<div class="row "  id= "imagePrev" style="margin-top: -10px; display: none;">
				<img id="imgDisplay" style="float: left; width: auto; height: 50px; margin-left: 16px;"/>
				<i class="glyphicon glyphicon-remove" style="cursor: pointer;" onclick="removeImage()"> </i>
				</div>
			</div>
		</div>
		
		<div id="publication_fields" style="display: none; ">
				<div class="row">
					<hr style="margin-top:3px;margin-bottom:0px; ">
					<div style="float: left; width:50px; font-size:14px;  background: #DDD; height: 34px" id="onproject">
						<h5 style="margin-top: 9px;"> Em: </h5>
					</div>
					
						
					
						<div style="float: left; width:460px;">
						<%= f.association :project, collection: current_user.projects.order(:name), label: false, :include_blank => "qual o projeto que você realizou essa atividade?", input_html: {id: "combo-input", onchange: "verifyPost(this)"} %>
						</div>
				</div>
				

				<div class="row" >
				<hr style="margin-top:0px;margin-bottom:3px; border-top: 1px solid #DDD;">
				<div style="width: 100px; float: right; margin-right: 0px;"  onclick="verifySubmit()">
					<%= f.submit "Publicar", class: 'btn btn-success', id: 'publication_submit', style: "background: #009688; padding-top: 2px; padding-bottom: 2px;" %>
				</div>


			</div>
		</div>

		
		
		<% end %>
	</div>

</div>
<script>
function imagePreview(input){

	if (input.files && input.files[0]) 
      {
      	$("#imagePrev").show();
      	$("#publication_fields").show();
        var filerdr = new FileReader();
        filerdr.onload = function(e) {
            $('#imgDisplay').attr('src', e.target.result);
        };
        filerdr.readAsDataURL(input.files[0]);
      }
};
function removeImage(){
	var input = document.getElementById("fileupload-example-4");
	input.value = "";
	$("#imagePrev").hide();

};
function showComments(id){
	var com = "#comments_" + id;
	$(com).slideToggle(500);

};

function verifyPost(input){

               	  if (input.value == "") {
               	  	document.getElementById('publication_submit').disabled = true;
               	  }else{
               	  	document.getElementById('publication_submit').disabled = false;
               	  }

               	  	
               };

function verifySubmit(){
		button = document.getElementById('publication_submit');
		if (button.disabled) {
               	 alert('Você deve selecionar um projeto para publicar');
        }
};

$(document).ready(function () {


			document.getElementById('publication_submit').disabled = true;

                $("#public_textarea").click(function(){
                	var el = document.getElementById('public_textarea');
                  el.style.height = "70px";
                  $("#publication_fields").show();


              });
               $("#public_textarea").blur(function(){
                  var el = document.getElementById('onproject');
                  
              });


        });

</script>

app/views/publications/_publication.html.erb
			<div class="water" style="margin-bottom:-7px;">
				<% if feed.sharing != nil %>
				<div class="eye-top">
					<%= image_tag(User.find(feed.sharing).avatar, class: "img-responsive avatarpost") %>
					<h5 style="padding-top:11px; color: #929292"><a style="color: #009688 !important"><%=User.find(feed.sharing).name%></a> compartilhou uma atividade há <%= time_ago_in_words(feed.created_at) %></h5>
				</div>
				<% else %>
				<div class="eye-top">
					<%= image_tag(feed.user.avatar, class: "img-responsive avatarpost") %>
					<h5 style="padding-top:11px; color: #929292"><%= link_to feed.user.name, feed.user, class: "user_link" %> realizou uma atividade há <%= time_ago_in_words(feed.created_at) %></h5>
				</div>

				<% end %>
				<div class="title-blue" style="margin-top:3px; border: 1px solid #EAEAEA">
					<div class="row" style="margin-left: 0px;">
						<div class="col-md-11" style="padding-left: 0px !important;">

						<div style="width: 44x; border: 1px solid #DDD; height: 44px;line-height:42px;float:left; margin-left: 0px; margin-top: -10px; margin-right: 5px;">
							<%= image_tag(feed.project.avatar, class: "projectpost") %>
						</div>

						<h4 style="text-align:left;padding-top:-2px; margin-top: -5px;"><%= link_to feed.project.name, feed.project, class: "user_link" %> </h4>
						<h5 style="padding-top:2px; text-align:left;">
							<%feed.project.interests.each do |i| %> 
							<%= i.name%>, 
							<%end%></h5>

						</div>
						<div class="col-md-1" style="padding-left: 0px !important; font-align: right; margin-top: -10px">
							<%if current_user == feed.user || current_user == feed.project.user %>
							<div class="dropdown" style="float: right; cursor: pointer">
			                      <span class="dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
			                        <span class="glyphicon glyphicon-chevron-down drop_icon"></span>
			                      </span>
			                      <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
			                        <li><%= link_to 'Editar', edit_publication_path(feed) %></li>
			                        <li><%= link_to 'Excluir', publication_path(feed), method: :delete, data: {confirm: "Tem certeza que deseja excluir essa publicação?"} %></li>
			                      </ul>
			                </div>
							<% end %>
						</div>
					</div>



					<% if feed.image.to_s != '' %>
					<div style="text-align: left; margin-top: 10px">
						<%= image_tag(feed.image, class: 'img-responsive') %>
					</div>
						<p style="text-align: justify; margin-left:0px; margin-top:0px;" class="publication_desc"><%= feed.description %></p>
					<% else %>
						<p style="text-align: justify; margin-left:0px; margin-top:5px;" class="publication_desc"><%= feed.description %></p>
					<% end %>
					
					<hr style="margin-top: 0px;margin-bottom: 10px;">
					<div style="text-align: left; margin-bottom: 10px; ">
					<%= link_to 'Compartilhar', share_publication_projects_path(publication: feed),data:{confirm: "Tem certeza?" }, class: "share_link"  %>
					<h6 style="float: right; color: #929292"> <%= shares_count(feed.shares.count) %> </h6>
					</div>
					<hr style="margin-top: 0px;margin-bottom: 10px;">
					<div style="text-align: left; margin-bottom: 10px;">
					<%= link_to comments_count(feed.comments.count), "javascript:;", class: "share_link", onclick: "showComments(#{feed.id})"  %>
					</div>
						
					<div style="text-align:left; margin-left:15px; display:none;" id="comments_<%= feed.id %>">
						<% feed.comments.each do |comment| %>
							<div class="row">
								<div class="" style="width: 515px; margin-bottom: 10px">
									<div style="weight: 30px" >
									<%= image_tag(comment.user.avatar, class: "commentpost",style: "margin-top: 0px") %>
									</div>
									  
  								
									<p style="width: 86%; padding-top:0px; line-height: 1.3em; padding-bottom: 0px;">
									<strong style="color: #009688"><%= comment.user.name %></strong>
										<%= comment.description %><br>
									</p>
							<div class="dropdown" >			
							<span style="color: #929292"> <%= time_ago_in_words(comment.created_at) %> </span> 
							<%if current_user == feed.user || current_user == feed.project.user || comment.user == current_user%>
			                      <span class="dropdown-toggle" style="cursor: pointer" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
			                        <span class="glyphicon glyphicon glyphicon-pencil drop_icon"></span>
			                      </span>
			                      <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
			                      	<% if comment.user == current_user %>
			                        <li> <a href = "#" data-toggle="modal" data-target="#editcomment_<%= comment.id %>"> Editar </a>
			                        </li>
			                        <% end %>
			                        <li> <%= link_to 'Excluir', destroy_comment_publications_path(id: comment.id), method: :delete, data: { confirm: 'Are you sure?'} %> </li>
			                      </ul>
			                
							<% end %>
							</div>
									
								</div>
							</div>
						<% end %>
					</div>
					<%= simple_form_for @comment, :url => create_comment_publications_path(@comment) do |f| %>
						<%= f.input :description, label: false, placeholder: "Escreva um comentário", input_html: {class: "comment_input", style: "font-size: 13px; "}%>
						<%= f.input :publication_id, :as => :hidden, :input_html => {:value =>  feed.id} %>
						  <div class="actions">
						    <% f.submit %>
						  </div>
					<% end %>

				</div>
			</div>
		<br>


<% if current_user.comments.each do |comment|%>
	<div class="modal fade" id="editcomment_<%= comment.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title" id="myModalLabel">Editando Comentário</h4>
	      </div>
	      <%= simple_form_for comment, :url => update_comment_publications_path(:id => comment.id) do |f| %>
	      <div class="modal-body">
	        	<%= f.input :description, label: false%>
	      </div>
	      <div class="modal-footer">
	        <%= f.submit "Salvar", class: "btn btn-default button_project button_submit"%>
	        <button type="button" class="btn btn-default button_project" data-dismiss="modal">Fechar</button>
	      </div>
	      <% end %>
	      
	    </div>
	  </div>
	</div>

	<% end %>
<% end %>

app/views/publications/edit.html.erb
<%= simple_form_for @publication do |f| %>
  <% if @publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
      <% @publication.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

        <div class="water" style="margin-bottom:-7px;">
        <div class="eye-top">
          <%= image_tag(@publication.user.avatar, class: "img-responsive avatarpost") %>
          <h5 style="padding-top:11px; color: #929292"><a style="color: #009688 !important"><%=@publication.user.name%></a> realizou uma atividade há <%= time_ago_in_words(@publication.created_at) %></h5>
        </div>

        <div class="title-blue" style="margin-top:3px; border: 1px solid #EAEAEA">
          <div class="row" style="margin-left: 0px;">
            <div class="col-md-11" style="padding-left: 0px !important;">
            <%= image_tag(@publication.project.avatar, class: "img-responsive projectpost") %>
            <h4 style="text-align:left;padding-top:-2px; margin-top: -5px;"><%= @publication.project.name %> </h4>
            <h5 style="padding-top:2px; text-align:left;">
              <%@publication.project.interests.each do |i| %> 
              <%= i.name%>, 
              <%end%></h5>

            </div>
          </div>



          <% if @publication.image.to_s != '' %>
          <div style="text-align: left; margin-top: 10px">
            <%= image_tag(@publication.image, class: 'img-responsive') %>
          </div>
          
            
          <% end %>
          <br>
         <%= f.input :description, label: false %>
           <div class="actions">
            <%= f.submit 'Salvar Edição', class: 'btn btn-default button_project button_submit' %>
              <%= link_to 'Cancelar', @publication, class: "btn btn-default button_project " %>
          </div>
        </div>
      </div>
    
<% end %>

app/views/publications/edit_comment.html.erb
<%= simple_form_for @comment, :url => update_comment_publications_path(:id => @comment.id) do |f| %>

<%= f.input :description%>
<%= f.input :publication_id, :as => :hidden, :input_html => {:value =>  @publication} %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publications/new.html.erb
<h1>New Publication</h1>

<%= render 'form' %>

app/views/publications/new_comment.html.erb
<%= simple_form_for @comment, :url => create_comment_publications_path(@comment) do |f| %>

<%= f.input :description%>
<%= f.input :publication_id, :as => :hidden, :input_html => {:value =>  @publication} %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publications/show.html.erb
<% feed = @publication %>
<%= render 'publication', feed: @publication %>
<script>

$('#comments_<%= @publication.id %>').show();
function showComments(id){
	var com = "#comments_" + id;
	$(com).slideToggle(500);

};
</script>