config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:index, :show, :list_abilities_interests] do
    collection do
      get 'close_window'
      get 'notifications'
      get 'messages'
    end
  end

  authenticated :user do
    root :to => "homee#index"
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  resources :conversations do
    resources :messages
  end

  resources :topics do
    collection do
      post 'create_post'
      patch 'update_post'
      delete 'destroy_post'
      get 'make_important'
      get 'make_not_important'
    end
  end
  resources :friends do
    collection do
      get 'friend_request'
      get 'cancel_request'
      delete 'refuse_request'
      get 'accept_request'
    end
  end
  resources :publications do
    collection do
      post 'create_comment'
      patch 'update_comment'
      delete 'destroy_comment'
    end
  end

  resources :tasks do
    collection do
      get 'move_do'
      get 'move_doing'
      get 'move_done'
      get 'accept'
      get 'enter_request'
      get 'quit_request'
      get 'quit_accept'

      patch 'quit_request'
      get 'quit_refuse'
      get 'refuse'
    end
  end
  resources :interests
  resources :abilities
  get 'projects/search_result' => 'projects#search_result', as: :search_result
  resources :projects do
    collection do
        get 'share_publication'
        get 'list_projects'
        get 'send_request'
        get 'accept_request'
        get 'refuse_request'
        get 'without_project'
        get 'follow'
        get 'unfollow'
      end
    end
  get 'chat_refresh' => 'homee#chat_refresh', as: :chat_refresh
  get 'projects/:id/members' => 'projects#members', as: :members_project
  get 'projects/:id/about' => 'projects#about', as: :about_project
  get 'projects/:id/request_list' => 'projects#request_list', as: :request_list
  get 'projects/:id/forum/create_topic' => 'topics#new', as: :create_topic
  get 'projects/:id/new_publication' => 'publications#new', as: :create_publication
  get 'projects/:id/new_comment' => 'publications#new_comment', as: :new_comment
  get 'projects/:id_project/publications/:id_publication/edit_comment' => 'publications#edit_comment', as: :edit_comment
  get 'projects/:id/new_task' => 'tasks#new', as: :create_task
  get 'projects/:id/forum/' => 'topics#index', as: :list_topics
  get 'projects/:id/forum/:id_topic' => 'topics#show_topic', as: :show_topic
  get 'projects/:id/forum/:id_topic/new_post' => 'topics#new_post', as: :new_post
  get 'projects/:id/forum/:id_topic/show_topic/:id_post' => 'topics#edit_post', as: :edit_post
  get 'projects/:id/tasks/' => 'tasks#index', as: :list_tasks
  get 'projects/:id/tasks/:id_task/edit' => 'tasks#edit', as: :edit_tasks
  get 'projects/:id/tasks/:id_task' => 'tasks#show', as: :show_tasks
  get 'cep/:cep' => 'cep#verificar'
  get 'users/:id/about' => 'users#about', as: :about_user
  get 'users/:id/friends' => 'users#friends', as: :friends_user
  get 'users/:id/projects' => 'users#projects', as: :projects_user
  get 'user/:id' => 'users#list_abilities_interests', as: :list_preferences

  

  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'sessions' => 'sessions#create', :as => 'login'
        post 'registrations' => 'registrations#create', :as => 'register'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
    end
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	include PublicActivity::Model

	belongs_to :user
	belongs_to :project

	has_many :posts, dependent: :destroy
  	has_many :activities, as: :trackable, class_name: 'PublicActivity::Activity', dependent: :destroy
  

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
before_action :set_topic_id, only: [:show_topic, :edit, :destroy]
before_action :set_post_id, only: [:edit_post]


def index
    @project = Project.find(params[:id])
    @topics = @project.topics.order(important: :desc)
end

def make_important
    topic = Topic.find(params[:topic])
    topic.important = true
    project = Project.find(topic.project_id)
    topic.save
    flash[:success] = 'Tópico fixado como importante.'
    redirect_to list_topics_path(project)
end

def make_not_important
    topic = Topic.find(params[:topic])
    topic.important = false
    project = Project.find(topic.project_id)
    topic.save
    redirect_to list_topics_path(project)
end

def new
	@topic = Topic.new
	@project = params[:id]
end

def show_topic
  @project = @topic.project
end

def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id
    @project = Project.find(@topic.project_id)
    respond_to do |format|

      if @topic.save
        @project.members.where(situation: 1).each do |member|
          if member.user_id != current_user.id
            @topic.create_activity(:create, :owner => User.find(member.user_id))
          end
        end
        format.html { redirect_to list_topics_path(@project), notice: 'Tópico criado com sucesso.' }
        format.json { render :show, status: :created, location: @project}
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

def edit
end

def update
  @topic = Topic.find(params[:id])
  @topic.update(topic_params)
  flash[:success] = 'Tópico atualizado com sucesso.'
  redirect_to controller: 'topics', action: 'index', id: @topic.project.id
end

def destroy
  project = @topic.project
  @topic.destroy
  flash[:success] = 'Tópico excluído com sucesso.'
  redirect_to controller: 'topics', action: 'index', id: project.id 
end




def new_post
  @post = Post.new
  @topic = params[:id_topic]
end

def create_post
  @post = Post.new(post_params)
  @post.user_id = current_user.id
  topic = Topic.find(@post.topic_id)
  respond_to do |format|
    if @post.save
      format.html { redirect_to controller: 'topics', action: 'show_topic', id: @post.topic.project.id, id_topic: @post.topic.id, notice: 'Post was successfully created.' }
      format.json { render :show, status: :created, location: topic}
    else
      format.html { render :new }
      format.json { render json: @topic.errors, status: :unprocessable_entity }
    end
  end
end

def edit_post
  @post_id = params[:id_post]
end

def update_post
  @post = Post.find(params[:id_post])
  @post.update(post_params)
  redirect_to controller: 'topics', action: 'show_topic', id: @post.topic.project.id, id_topic: @post.topic.id, notice: 'Post was successfully updated.'
end

def destroy_post
  @post = Post.find(params[:id])
  topic = @post.topic
  @post.destroy
  redirect_to controller: 'topics', action: 'show_topic', id_topic: topic.id, id: topic.project.id, notice: 'Post was successfully destroyed.' 
end


  private
    # Use callbacks to share common setup or constraints between actions.
    def load_activities
      @activities = PublicActivity::Activity.order('created_at DESC').limit(20)
    end

    def set_topic
      @topic = Topic.find(params[:id])
    end

     def set_topic_id
      @topic = Topic.find(params[:id_topic])
    end

    def set_post_id
      @post = Post.find(params[:id_post])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:topic_title, :description, :important, :user_id, :project_id)
    end

    def post_params
      params.require(:post).permit(:description, :user_id, :topic_id)
    end
end

app/views/topics/_edit_post.html.erb
<div class="modal fade" id="edit_post_<%=post.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Postar Resposta</h4>
      </div>
      <%= simple_form_for post, :url => update_post_topics_path(post, :id_post => post.id) do |f| %>
      <div class="modal-body">
          <%= f.input :description%>
      </div>
      <div class="modal-footer">
        <%= f.submit "Salvar", class: "btn btn-default button_project button_submit"%>
        <button type="button" class="btn btn-default button_project" data-dismiss="modal">Fechar</button>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/topics/_edit_topic.html.erb
<div class="modal fade" id="edit_topic_<%= topic.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Editando Topico</h4>
      </div>
      <%= simple_form_for topic do |f| %>
      <div class="modal-body">
          <%= f.input :topic_title%>
          <%= f.input :description%>
      </div>

      <div class="modal-footer">
        <%= f.submit "Salvar", class: "btn btn-default button_project button_submit"%>
        <button type="button" class="btn btn-default button_project" data-dismiss="modal">Fechar</button>
      </div>
      <% end %>

    </div>
  </div>
</div>

<script>

</script>

app/views/topics/_new_post.html.erb
<div class="modal fade" id="new_post" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Postar Resposta</h4>
      </div>
      <%= simple_form_for post, :url => create_post_topics_path(post) do |f| %>
      <div class="modal-body">
          <%= f.input :description, label: "Descrição"%>
          <%= f.input :topic_id, :as => :hidden, :input_html => { :value =>  @topic.id} %>
      </div>

      <div class="modal-footer">
        <%= f.submit "Salvar", class: "btn btn-default button_project button_submit"%>
        <button type="button" class="btn btn-default button_project" data-dismiss="modal">Fechar</button>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/topics/_new_topic.html.erb
<div class="modal fade" id="new_topic" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Criando Topico</h4>
      </div>
      <%= simple_form_for topic do |f| %>
      <div class="modal-body">
          <%= f.input :topic_title, label: "Título do Tópico"%>
          <%= f.input :description, label: "Descrição"%>
          <%= f.input :project_id, :as => :hidden, :input_html => { :value =>  project.id } %>
      </div>

      <div class="modal-footer">
        <%= f.submit "Salvar", class: "btn btn-default button_project button_submit"%>
        <button type="button" class="btn btn-default button_project" data-dismiss="modal">Fechar</button>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/topics/create_post.html.erb
<%= simple_form_for(@post) do |f| %>

<%= f.input :description%>
<%= f.input :project_id, :as => :hidden, :input_html => { :value =>  @project } %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<%= simple_form_for @topic, :id => @topic.id do |f| %>

<%= f.input :topic_title%>
<%= f.input :description%>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit_post.html.erb
<%= simple_form_for @post, :url => update_post_topics_path(@post, :id => @post_id) do |f| %>

<%= f.input :description%>
<%= f.input :project_id, :as => :hidden, :input_html => { :value =>  @project } %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/index.html.erb
<%= render 'projects/projectnav'%>

<div class="water" style="border: 1px solid #EAEAEA">
  <div class="title-blue-publication " style="padding-top: 15px;">
  <div class="row" style="text-align: left"> 
    <div class="col-md-12" style="margin-bottom: 10px;"> 
      <h5 style="font-size:14px; margin-bottom: 5px; font-weight: bold; color: #333;">
      <div style=""> <a href="#" class="btn button_project button_inactive" data-toggle="modal" data-target="#new_topic">  Nova Discussão  </a> </div>
       </h5> 
   </div>


<%= render 'new_topic', topic: Topic.new, project: @project %>

<% @topics.order(important: :desc, updated_at: :desc).each do |p| %>

  <div class="col-md-12">
  <div style="width: 18px; height: 30px; float: left;"> 
    <% if p.important %>
      <%= link_to make_not_important_topics_path(topic: p.id), class: "user_link" do %> 
        <span class="glyphicon glyphicon-pushpin fixed-topic <%= topic_fixed(p) %>" style="font-size:14px;"> </span> 
      <% end %>
    <% else %>
      <%= link_to make_important_topics_path(topic: p.id), class: "user_link" do %> 
        <span class="glyphicon glyphicon-pushpin fixed-topic <%= topic_fixed(p) %>" style="font-size:14px;"> </span>
      <% end %>
    <% end %>
  </div>
  <%= link_to p.topic_title, show_topic_path(id: @project.id, id_topic: p.id), class: "panel-title user_link", style: "font-size: 16px; font-weight: ;" %> 
              <span class="dropdown-toggle" style="cursor: pointer" id="dropdownMenu<%= p.id %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              <span class="glyphicon glyphicon-pencil drop_icon" style="font-size: 12px"> </span> 
              </span>
              <span style="color: #AAA; float: right;"> <%= posts_count(p.posts.count) %> </span>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenu<%= p.id %>" style="top: auto !important; left: auto !important;">
                  <li> <%= link_to 'Editar', "#", data:{toggle: 'modal', target: "#edit_topic_#{p.id}"} %> </li>
                  
                  <li> <%= link_to 'Excluir', topic_path(id_topic: p.id), method: :delete, data: {confirm: "Tem certeza que deseja excluir essa publicação?"} %> </li>
              </ul>
  <h6 style="font-size: 12px; color: #777"> Criado por <%= p.user.name %> <span style="float: right; color: #AAA"> <%= p.posts.count == 0  ? "" : "Ultima resposta por #{p.posts.last.user.name}" %> </span> </h6>
  <hr style="margin-top: 5px; margin-bottom:5px;">
  </div>

  <%= render 'edit_topic', topic: p%>
  
  <!--
  <div class="panel-body">
    <%= p.description %>

   </div>
  <div class="panel-body">
    <%= p.important %>
  </div>
  <div class="panel-body">
  	<%= link_to "Editar", edit_topic_path(id_topic: p.id) %>
  	<br>
  	<%= link_to "Deletar", topic_path(id_topic: p.id), method: :delete, data: { confirm: 'Are you sure?'} %>
    <br>
    <% if p.important == false %>
    <%= link_to 'Fixar como importante', make_important_topics_path(topic: p.id) %>
    <% else %>
    <%= link_to 'Desmarcar como Importante', make_not_important_topics_path(topic: p.id) %>
    <% end %>
  
  </div>
  
  </div>
  -->
<% end %>
 </div>
</div>
</div>

app/views/topics/new.html.erb
<%= simple_form_for(@topic) do |f| %>

<%= f.input :topic_title%>
<%= f.input :description%>
<%= f.input :project_id, :as => :hidden, :input_html => { :value =>  @project } %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/new_post.html.erb
<%= simple_form_for @post, :url => create_post_topics_path(@post) do |f| %>

<%= f.input :description%>
<%= f.input :topic_id, :as => :hidden, :input_html => { :value =>  @topic} %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/show_topic.html.erb
<%= render 'projects/projectnav'%>

<div class="water" style="border: 1px solid #EAEAEA">
  <div class="title-blue-publication " style="padding-top: 15px;">
    <div class="row">
      <div class="col-md-12" style="text-align:left; margin-bottom: 20px; ">
        <h5 style="font-size:17px; margin-bottom: 5px; color: #333;"><%=  @topic.topic_title %>
        <div style="float: right; padding-right:15px;"> <a href="#" class="btn button_project button_inactive" data-toggle="modal" data-target="#new_post">  Nova Resposta  </a> </div>
      </h5> 
      </div>  
      <div class="col-md-12">
        <div class="col-md-2">
          <%= image_tag(@topic.user.avatar, class: "img-responsive") %>
        </div>
        <div class="col-md-10" style="text-align: left; padding-left:0px;">
          <%= link_to @topic.user.name, @topic.user, class: "user_link" %>
          <span style="float: right; color:#AAA; font-size: 11px;"> 
            <%= @topic.created_at.to_formatted_s(:long_ordinal)  %>
            <%= @topic.created_at == @topic.updated_at ? "" : "- Editado"  %> 
            <% if current_user == @topic.user || @topic.project.user == current_user %>
              <%= link_to '', "#", class: "glyphicon glyphicon-pencil",data:{toggle: 'modal', target: "#edit_topic_#{@topic.id}"} %> 
            <% end %>
          </span>
          <br>
          <p> <%= @topic.description %> </p>
        </div>
      </div>

      <%= render 'edit_topic', topic: @topic%>

      <% @topic.posts.each do |post|%>
      <div class="col-md-12" style="margin-top: 10px;">
        <hr style="margin-bottom: 5px; margin-top: 0px;"> 
        <div class="col-md-2">
          <%= image_tag(post.user.avatar, class: "img-responsive") %>
        </div>
        <div class="col-md-10" style="text-align: left; padding-left:0px;">
          <%= link_to post.user.name, post.user, class: "user_link" %>
          <span style="float: right; color:#AAA; font-size: 11px;"> 
            <%= post.created_at.to_formatted_s(:long_ordinal)  %> 
            <%= post.created_at == post.updated_at ? "" : "- Editado"  %> 
            <% if current_user == post.user || @topic.project.user == current_user %>
              <%= link_to '', "#", class: "glyphicon glyphicon-pencil",data:{toggle: 'modal', target: "#edit_post_#{post.id}"} %> 
            <% end %>
          </span>
          <p> <%= post.description %> </p>
        </div>
        <%= render 'edit_post', post: post%>
      </div>
      <% end %>

      <h5 style="font-size:14px; margin-bottom: 5px; font-weight: bold; color: #333;">
        <div style="float: right; padding-right:30px;"> <a href="#" class="btn button_project button_inactive" data-toggle="modal" data-target="#new_post">  Nova Resposta  </a> </div>
      </h5> 
    </div>
  </div>
</div>
<%= render 'new_post', topic: @topic, post: Post.new %>
<!--
<p id="notice"><%= notice %></p>

<p>
  <strong>Título:</strong>
  <%= @topic.topic_title %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @topic.description %>
</p>



<table>
  <thead>
    <tr>
      <th>user_id</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topic.posts.each do |post| %>
      <tr>
        <td><%= post.user.email %></td>
        <td><%= post.description %></td>
        <td><%= link_to 'Editar', controller: 'topics', action: 'edit_post', id: post.topic.project.id, id_topic: post.topic.id, id_post: post.id %></td>
        <td><%= link_to 'Excluir', destroy_post_topics_path(id: post.id), method: :delete, data: { confirm: 'Are you sure?'}  %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<%= link_to 'Postar', new_post_path%>
-->